export PATH=$PATH:\
/bin:\
/Library/TeX/texbin:\
/opt/local/bin:\
/opt/local/sbin:\
/opt/X11/bin:\
/sbin:\
/Users/marekkowalczyk/.opam/default/bin:\
/Users/marekkowalczyk/go/bin:\
/usr/bin:\
/usr/local/bin:\
/usr/local/Cellar/gnupg/2.2.20/bin:\
/usr/local/opt/bison/bin:\
/usr/local/opt/flex/bin:\
/usr/local/opt/fzf/bin:\
/usr/local/opt/openssl/bin:\
/usr/local/plan9/bin:\
/usr/sbin:\
/usr/texbin/Users/marekkowalczyk/.rvm/gems/ruby-2.5.1/bin:\
/Users/marekkowalczyk/.rvm/gems/ruby-2.5.1@global/bin:\
/Users/marekkowalczyk/.rvm/rubies/ruby-2.5.1/bin:\
/Users/marekkowalczyk/.rvm/bin
